# Generated by Django 5.1.15 on 2026-08-23 21:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_ugc_creator_rights_requests'),
        ('workspaces', '0004_workspace_discovery_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCCreatorCollaborationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_token', apps.common.encryption.EncryptedTextField()),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hint', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Awaiting creator'), ('accepted', 'Accepted by creator'), ('declined', 'Declined by creator'), ('superseded', 'Replaced'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('terms_snapshot', apps.common.encryption.EncryptedJSONField(default=dict)),
                ('terms_digest', models.CharField(max_length=64)),
                ('response_note', apps.common.encryption.EncryptedTextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_invites', to='common.ugccreatorcollaboration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ugc_creator_collaboration_invites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugc_creator_collaboration_invites', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'common_ugc_creator_collaboration_invite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status', 'expires_at'], name='ugc_collab_inv_status_idx'), models.Index(fields=['collaboration', '-created_at'], name='ugc_collab_inv_collab_idx')],
            },
        ),
    ]
