# Generated by Django 5.1.15 on 2026-08-23 23:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_creator_collaboration_invites'),
        ('media_library', '0003_pendingupload'),
        ('workspaces', '0004_workspace_discovery_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCCreatorCollaborationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Awaiting review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted')], db_index=True, default='submitted', max_length=30)),
                ('source_url', models.URLField(blank=True, default='', max_length=2000)),
                ('creator_note', apps.common.encryption.EncryptedTextField(blank=True, default='')),
                ('review_note', apps.common.encryption.EncryptedTextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='common.ugccreatorcollaboration')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ugc_creator_deliveries', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_collaboration_deliveries', to='common.ugcsubmission')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugc_creator_collaboration_deliveries', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'common_ugc_creator_collaboration_delivery',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='UGCCreatorCollaborationDeliveryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='common.ugccreatorcollaborationdelivery')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_collaboration_delivery_attachments', to='media_library.mediaasset')),
            ],
            options={
                'db_table': 'common_ugc_creator_collaboration_delivery_asset',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ugccreatorcollaborationdelivery',
            index=models.Index(fields=['workspace', 'status', '-submitted_at'], name='ugc_delivery_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ugccreatorcollaborationdelivery',
            index=models.Index(fields=['collaboration', '-revision_number'], name='ugc_delivery_collab_idx'),
        ),
        migrations.AddConstraint(
            model_name='ugccreatorcollaborationdelivery',
            constraint=models.UniqueConstraint(fields=('collaboration', 'revision_number'), name='ugc_collab_delivery_revision_uniq'),
        ),
        migrations.AddIndex(
            model_name='ugccreatorcollaborationdeliveryasset',
            index=models.Index(fields=['delivery', 'position'], name='ugc_delivery_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='ugccreatorcollaborationdeliveryasset',
            constraint=models.UniqueConstraint(fields=('delivery', 'position'), name='ugc_delivery_asset_position_uniq'),
        ),
    ]
