"""Mobile-optimized moderation queue rendering.

The regular moderation queue intentionally supports a dense desktop review view.
On phones, rendering 100 full moderation cards at once is expensive (especially
in Safari because each card can contain media, forms, and enhancement hooks).
This view keeps the exact same moderation semantics while slicing the initial
server response to a small page for mobile user agents.
"""

from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render

from apps.members.decorators import require_permission

from .models import UGCReport, UGCSubmission
from .ugc_views import (
    VALID_TABS,
    _discovered_q,
    _get_workspace,
    _pending_submission_q,
    _queue_counts,
)


MOBILE_PAGE_SIZE = 16
DESKTOP_PAGE_SIZE = 100


def _is_mobile_request(request):
    ua = (request.META.get("HTTP_USER_AGENT") or "").lower()
    return any(token in ua for token in ("iphone", "ipod", "android", "mobile"))


def _positive_page(raw):
    try:
        return max(1, int(raw or 1))
    except (TypeError, ValueError):
        return 1


@login_required
@require_permission("manage_workspace_settings")
def moderation_queue(request, workspace_id):
    workspace = _get_workspace(request, workspace_id)
    tab = request.GET.get("tab", "pending")
    if tab not in VALID_TABS:
        tab = "pending"

    qs = (
        UGCSubmission.objects.for_workspace(workspace.id)
        .select_related("contributor", "media_asset", "moderated_by")
        .annotate(
            open_report_count=Count(
                "reports",
                filter=Q(reports__status__in=[UGCReport.Status.OPEN, UGCReport.Status.REVIEWING]),
                distinct=True,
            )
        )
    )

    if tab == "discovered":
        qs = qs.filter(status=UGCSubmission.Status.PENDING).filter(_discovered_q())
    elif tab == "pending":
        qs = qs.filter(status=UGCSubmission.Status.PENDING).filter(_pending_submission_q())
    elif tab == "approved":
        qs = qs.filter(status=UGCSubmission.Status.APPROVED)
    elif tab == "reported":
        qs = qs.filter(
            reports__status__in=[UGCReport.Status.OPEN, UGCReport.Status.REVIEWING]
        ).distinct()
    elif tab == "removed":
        qs = qs.filter(status=UGCSubmission.Status.REMOVED)

    kind = request.GET.get("kind", "").strip()
    if kind in dict(UGCSubmission.Kind.choices):
        qs = qs.filter(kind=kind)
    else:
        kind = ""

    mobile = _is_mobile_request(request)
    page_size = MOBILE_PAGE_SIZE if mobile else DESKTOP_PAGE_SIZE
    page = _positive_page(request.GET.get("page")) if mobile else 1
    total_items = qs.count()
    total_pages = max(1, (total_items + page_size - 1) // page_size)
    page = min(page, total_pages)
    start = (page - 1) * page_size
    submissions = list(qs[start : start + page_size])

    reported_ids = [submission.id for submission in submissions if submission.open_report_count]
    reports_by_submission = {}
    if reported_ids:
        reports = (
            UGCReport.objects.for_workspace(workspace.id)
            .filter(
                submission_id__in=reported_ids,
                status__in=[UGCReport.Status.OPEN, UGCReport.Status.REVIEWING],
            )
            .select_related("reporter")
            .order_by("-created_at")
        )
        for report in reports:
            reports_by_submission.setdefault(report.submission_id, []).append(report)

    for submission in submissions:
        submission.active_reports = reports_by_submission.get(submission.id, [])

    context = {
        "workspace": workspace,
        "submissions": submissions,
        "active_tab": tab,
        "active_kind": kind,
        "kind_choices": UGCSubmission.Kind.choices,
        "queue_counts": _queue_counts(workspace),
        "ugc_mobile_page": page if mobile else None,
        "ugc_mobile_page_size": page_size if mobile else None,
        "ugc_mobile_total_items": total_items if mobile else None,
        "ugc_mobile_total_pages": total_pages if mobile else None,
    }
    response = render(request, "ugc/moderation_queue.html", context)
    if mobile:
        # Used by support/debugging and harmless to intermediaries. The actual
        # paging UI is generated by the mobile JS from the URL + active tab.
        response["X-UGC-Mobile-Page"] = str(page)
        response["X-UGC-Mobile-Page-Size"] = str(page_size)
        response["X-UGC-Mobile-Total"] = str(total_items)
    return response
